DROP TABLE IF EXISTS user CASCADE;

CREATE TABLE duck (
	user_id integer generated by default as identity,
	firstName varchar(255) not null,
	lastName varchar(255) not null,
	userName varchar(255) not null,
	password varchar(255) not null,
	primary key (user_id)
);


ALTER TABLE duck add constraint UK_8qrhl5wlohdjoko9nrorkdjkp unique (name);

