DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS todo CASCADE;

CREATE TABLE user (
	id integer generated by default as identity,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	user_name varchar(255) not null,
	password varchar(255) not null,
	primary key (id)
);

CREATE TABLE todo (
	todo_id integer generated by default as identity,
	title varchar(255) not null,
	memo varchar(255) not null,
	important boolean,
	fk_user_id integer,
	primary key (todo_id)
);

ALTER TABLE user add constraint UK_8qrhl5wlohdjoko9nrorkdjkp unique (user_name);
ALTER TABLE todo add constraint FKdtss7ab4sx4oagfqyacono43a foreign key (fk_user_id) references user on delete cascade;

