DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS todo CASCADE;
CREATE TABLE user (
	id integer generated by default as identity,
	firstName varchar(255) not null,
	lastName varchar(255) not null,
	userName varchar(255) not null,
	password varchar(255) not null,
	fk_todo_id integer,
	primary key (id)
);

CREATE TABLE todo (
	id integer generated by default as identity,
	title varchar(255) not null,
	memo varchar(255) not null,
	dateCreated datetime not null,
	dateCompleted datetime not null,
	important boolean,
	user_id integer,
	fk_user_id integer,
	primary key (id)
);


ALTER TABLE user add constraint UK_8qrhl5wlohdjoko9nrorkdjkp unique (password);
ALTER TABLE user add constraint FKdtss7ab4sx4oagfqyacono43a foreign key (fk_todo_id) references todo on delete cascade;
#This is a comment
